(function(g){var window=this;'use strict';var Vxb=function(a,b){g.W.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],W:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",W:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",W:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",W:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",W:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.xT(a,"Agrandir","i"));this.update({"data-title-no-tooltip":"Agrandir"});this.addOnDisposeCallback(g.vT(b.Se(),this.element))},Wxb=function(a){g.W.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.nh);this.T(a,"onStateChange",this.Aea)},Xxb=function(a){g.eV.call(this,a);
this.B=new g.HJ(this);this.j=new Wxb(this.player);this.j.hide();g.FT(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.Gv(a.getRootNode(),"ytp-player-minimized",!0))};
g.x(Vxb,g.W);Vxb.prototype.onClick=function(){this.J.ib("onExpandMiniplayer")};g.x(Wxb,g.W);g.k=Wxb.prototype;
g.k.show=function(){this.j=new g.uv(this.y5,null,this);this.j.start();if(!this.G){this.tooltip=new g.pX(this.player,this);g.L(this,this.tooltip);g.FT(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.le=new g.RV(this.player);g.L(this,this.le);this.B=new g.W({I:"div",S:"ytp-miniplayer-scrim"});g.L(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.o0);var a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],W:{"aria-label":"Fermer"},V:[g.NE()]});g.L(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.VU);a=new Vxb(this.player,this);g.L(this,a);a.Ja(this.B.element);this.C=new g.W({I:"div",S:"ytp-miniplayer-controls"});g.L(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.o0);var b=new g.W({I:"div",S:"ytp-miniplayer-button-container"});g.L(this,b);b.Ja(this.C.element);a=new g.W({I:"div",S:"ytp-miniplayer-play-button-container"});g.L(this,a);a.Ja(this.C.element);var c=new g.W({I:"div",S:"ytp-miniplayer-button-container"});
g.L(this,c);c.Ja(this.C.element);this.N=new g.BW(this.player,this,!1);g.L(this,this.N);this.N.Ja(b.element);b=new g.AW(this.player,this);g.L(this,b);b.Ja(a.element);this.nextButton=new g.BW(this.player,this,!0);g.L(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.iX(this.player,this);g.L(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.GW(this.player,this);g.L(this,this.progressBar);g.FT(this.player,this.progressBar.element,4);this.D=new g.W({I:"div",S:"ytp-miniplayer-buttons"});
g.L(this,this.D);g.FT(this.player,this.D.element,4);a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],W:{"aria-label":"Fermer"},V:[g.NE()]});g.L(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.VU);a=new g.W({I:"button",Ka:["ytp-miniplayer-replay-button","ytp-button"],W:{"aria-label":"Fermer"},V:[g.Rya()]});g.L(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.aca);this.T(this.player,"presentingplayerstatechange",this.z5);this.T(this.player,"appresize",this.kc);
this.T(this.player,"fullscreentoggled",this.kc);this.kc();this.G=!0}this.player.getPlayerState()!==0&&g.W.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.xa.call(this)};
g.k.VU=function(){this.player.stopVideo();this.player.ib("onCloseMiniplayer")};
g.k.aca=function(){this.player.playVideo()};
g.k.o0=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.nh=function(){g.Gv(this.player.getRootNode(),"ytp-player-minimized",this.player.isMinimized())};
g.k.Cg=function(){this.progressBar.Tc();this.K.Tc()};
g.k.y5=function(){this.Cg();this.j&&this.j.start()};
g.k.z5=function(a){g.qF(a.state,32)&&this.tooltip.hide()};
g.k.kc=function(){g.z4a(this.progressBar,0,this.player.ob().getPlayerSize().width,!1);g.HW(this.progressBar)};
g.k.Aea=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Se=function(){return this.tooltip};
g.k.iy=function(a,b,c,d,e){var f=0,h=d=0,l=g.Xs(a);if(b){c=g.Bv(b,"ytp-prev-button")||g.Bv(b,"ytp-next-button");var m=g.Bv(b,"ytp-play-button"),n=g.Bv(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Vs(b,this.element),h=b.x,f=b.y-12):n&&(h=g.Bv(b,"ytp-miniplayer-button-top-left"),f=g.Vs(b,this.element),b=g.Xs(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.ob().getPlayerSize().width;e=f+(e||0);l=g.ze(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.x(Xxb,g.eV);g.k=Xxb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.Gv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.eV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.dn=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.dV("miniplayer",Xxb);})(_yt_player);
